### ISSUE TITLE
DIČ/IČ DPH vo výstupe API RPO

### ISSUE THREAD

**Issue by romanmatyus** [slovensko-digital/ekosystem#11]
JSON výstup v API RPO neobsahuje DIČ a IČ DPH subjektu.

**Comment by jsuchal** [comment]
Toto je by-design kedze zdrojove data tieto udaje neobsahuju. Mame api v https://ekosystem.slovensko.digital/sluzby/autoform kde su konsolidovane data. Pripadne premiove api, ktore tieto konsolidovane data spristupnuje. Co potrebujete spravit?
