### ISSUE TITLE
Hľadanie filtrovanie záznamov v API RPO

### ISSUE THREAD

**Issue by romanmatyus** [slovensko-digital/ekosystem#12]
API URL: https://datahub.ekosystem.slovensko.digital/api/data/rpo/organizations{?limit,name,ipo}
## Parametre

| Názov | Typ | Predvolená hodnota | Popis |  |
| --- | --- | --- | --- | --- |
| name | string |  | Názov subjektu alebo jeho časť. Možné použiť _%slovensko%_ pre case insensitive vyhľadávanie kdekoľvek v názve subjektu. |  |
| ipo | integer |  | IČO subjektu alebo jeho časť. Možné použiť _345%_ pre vyhľadávanie kdekoľvek v IČO subjektu. |  |
| limit | integer | 10 | Počet vrátených položiek |  |
## Návratová hodnota

``` json
[
    {
        "id": 624271,
        "established_on":"2006-03-01",
        // ...
    },
    // Rovnaké záznamy ako pre https://datahub.ekosystem.slovensko.digital/api/data/rpo/organizations/:id
]
```

**Comment by jsuchal** [comment]
@romanmatyus na toto mame sluzbu autoform https://ekosystem.slovensko.digital/sluzby/autoform, ktora vrati konsolidovane udaje. API vie vyhladavat aj podla mena aj podla ico (aj prefixy). Aky je Vas pripad pouzitia?

**Comment by jsuchal** [comment]
@romanmatyus toto API bolo uz implementovane a je dostupne po registracii na webe Autoformu. 

https://platforma.slovensko.digital/t/autoform-api-vyhladavanie-podla-obchodneho-mena/4782 diskusia k tomu bola aj tu.

Toto teda zatvaram ako hotove.
