### ISSUE TITLE
Rozdeliť / Rozbiť issues na menšie

### ISSUE THREAD

**Issue by eastcode-sessions** [slovensko-digital/ekosystem#14]
Napríklad na  Helicopter/1day/1hour

UC:
Ako programátor o desiatej večer by som s niečím helpol na 3 hodniky. Ale nemám na to obsiahnuť celú tému za tak krátky čas. 
Potrebujem návod čo premeniť na kód.

Podobne to asi bude platiť aj pre Devops, UX designers etc.

**Comment by jsuchal** [comment]
Toto neni zly napad. Nejake labels - small, medium, large, epic. By sa bodol. Pripadne to mozeme spajat aj do github projects. https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/ aj ked to je take dost manualne.

My interne pouzivame zatial radsej Waffle https://waffle.io/slovensko-digital/ekosystem

Co ty na to?
