### ISSUE TITLE
Report - autorske prava

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/ekosystem#17]
Zaujimala by nas statistika o vyuzivani priamych rokovacich konani pri nakupe IKT/IT.

- [ ] vytiahnut kolko je vlastne PRK (priame rokovacie konania)
- [ ] vytiahnut kolko PRK je kvoli autorskym pravam
- [ ] sumy podla dodavatelov, objednavatelov, rokoch etc

Idealne cez data z ekosystemu / datahub.

**Comment by miro-janosik** [comment]
Nič o tom neviem, ale databázy mám rád, takže niečo skúsim pohľadať. Zatiaľ nič nesľubujem, ozvem sa keď niečo budem mať.

**Comment by miro-janosik** [comment]
Zatial nic nemam (a ani som s tym poriadne nezacal) a stale som vytazeny. 
Takze vyzyvam niekoho dalsieho, aby zapracoval na tejto issue.

**Comment by lubosvanta** [comment]
posielam prehlad z datahubu

201 PRK pre IKT/IT celkovo od roku 2014
185 PRK pre IKT/IT na zaklade vyhradnych prav od roku 2014

identifikacia IKT/IT na zaklade cpv kodov (common procurement vocabulary), toto su zakladne, pod ktore som nasiel zeby mali spadat, aj ked asi moze byt nieco skryte pod inym kodom v inej kategorii
302 Počítačové zariadenia
32  Rozhlas, televízia, komunikácie, telekomunikácie a príbuzné zariadenia 
48  Softvérové balíky a informačné systémy 
72  Služby informačných technológií

detail podla obstaravatelov,dodavatelov 
[PRK.xlsx](https://github.com/slovensko-digital/ekosystem/files/1873107/PRK.xlsx)
[PRK_SQL.txt](https://github.com/slovensko-digital/ekosystem/files/1873147/PRK_SQL.txt)

**Comment by jsuchal** [comment]
@lubosvanta toto je fajnove.

**Comment by jsuchal** [comment]
Mozno by stalo za to spravit report v nasom metabase https://bi.ekosystem.slovensko.digital/ spravim ti konto?

**Comment by lubosvanta** [comment]
kludne sprav, pozriem ake su tam moznosti
