### ISSUE TITLE
Chybajuce data obstaravani po 6. novembri 2017

### ISSUE THREAD

**Issue by bundala** [slovensko-digital/ekosystem#19]
/api/data/crz/contracts/sync nevracia ziadne data pre datumy vacsie ako 6. november 2017.

Napriklad

https://datahub.ekosystem.slovensko.digital/api/data/crz/contracts/sync?last_id=0&since=2017-11-07T13%3A54%3A05.176752Z

vrati []

**Comment by jsuchal** [comment]
@mirrec vies preverit?

**Comment by mirrec** [comment]
@bundala zlyhal nam proces, ktory tahal nove data. Uz je to fixnute a data su uz aktualne.

**Comment by jsuchal** [comment]
Dakujeme za bugreport!
