### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by saberduck** [slovensko-digital/ekosystem#3]
Bolo by mozne spravit csv export dat? Na niektore ucely to moze byt praktickejsie ako SQL.

**Comment by jsuchal** [comment]
Export do csv nie je problem, problem je ako si clovek vysklada to co chce. SQL je pre programatora, nejake GUI moze byt zase prilis limitujuce.

Ako by ste si to predstavovali, resp. ake data by ste potrebovali?

**Comment by saberduck** [comment]
Predstavoval by som si to tak, ze rovnako ako je teraz na stiahnutie subor .sql , tak by bol k dispozicii na stiahnutie aj subor .csv pre kazdu tabulku (zkomprimovany). Pripadne jeden tar.gz, v ktorom by boli csv subory celeho datasetu.

**Comment by jsuchal** [comment]
@saberduck to sa spravit da bez problemov, ale kedze su tie tabulky normalizovane, tak ich pouzitie v taktomto formate by bolo znacne limitovane. 

skusme krok spat. ake data sa pokusate ziskat a preco?

**Comment by saberduck** [comment]
Napr. by som chcel tie data spracovavat v R alebo nahrat na Google BigQuery . Myslim ze csv je open datach bezne pouzivany a jeden z najuniverzalnejsich formatov.

**Comment by jsuchal** [comment]
Ano CSV je bezne pouzivany aj univerzalny, lenze malo pouzitelny bez denormalizacie. bigquery je dobry point. tam by to malo zmysel viac. ale to sme spat v SQL :)

**Comment by saberduck** [comment]
Takze bude k dispozicii v blizkej buducnosti endpoint na stiahnutie csv dat? Kludne to moze byt v nejakej denormalizovanej forme. Pripadne, ak s tym treba pomoct, tak povedzte ako.

**Comment by jsuchal** [comment]
@saberduck "v nejakej denormalizovanej forme" je presne ten problem. ake data na aky ucel potrebujete. lebo denormalizovanu formu musime vymysliet.

**Comment by Xubor** [comment]
To už mi príde jednoduchšie spraviť konvertor sql dump -> csv. Kto chce, použije.

**Comment by jsuchal** [comment]
@saberduck ako toto? Mame predstavu aku denormalizovanu formu by to malo dat?

**Comment by saberduck** [comment]
Bohuzial, nemal som cas sa tomu venovat, a v blizkej dobe asi ani nebudem mat.  Za mna mozte ticket zatvorit.
