### ISSUE TITLE
Protocol relative URL - anti-pattern

### ISSUE THREAD

**Issue by mareksuscak** [slovensko-digital/ekosystem#4]
Takzvané protocol relative URL adresy sa dnes už moc [neodporúčajú](http://www.paulirish.com/2010/the-protocol-relative-url/). Ak je dostupné SSL tak všetko by malo smerovať na zabezpečený endpoint. 

Všimol som si ich použitie v manuále autoformu. Je nejako opodstatnené?

<img width="831" alt="screen shot 2016-08-19 at 15 36 50" src="https://cloud.githubusercontent.com/assets/613647/17811395/cd1e16d8-6622-11e6-8df3-65ad3d287dbf.png">

**Comment by jsuchal** [comment]
Pravda, uz si ani nespominam preco takto. Opravime.

**Comment by mirrec** [comment]
@mareksuscak Fixnute, dakujeme.
